### PR TITLE
bugfix: no need to retrieve crl if read from local sucessfully.

### PR DESCRIPTION
**Pull request by dotmonkey**

### CODE REVIEW

**Comment by llemeurfr** [comment]
From the point of view of the LCP spec, if the CRL is available locally AND has been in cache for less than **24 hours**, this CRL will be used and it should not be fetched.

**Comment by dotmonkey** [comment]
@llemeurfr please check the code. this PR just prevent retrieving **ONLY** when the cache is **VALID**.   by the way, the cache limit in the code is 7 days.

**Comment by mickael-menu** [comment]
@dotmonkey Thanks for spotting this, the code looks right to me and I'll merge it when I have the time to test it.

@llemeurfr 
> From the point of view of the LCP spec, if the CRL is available locally AND has been in cache for less than 24 hours, this CRL will be used and it should not be fetched.

I think we always used 7 days for iOS and Android. I can't find any mention of 24 hours in the spec, is it documented somewhere?

**Comment by llemeurfr** [comment]
Just wanted "approve" from the lcp spec axis. I checked the code quickly, didn't look at the `expiration` value (7 days you say; ok this is easy for change to 1 if we decide so). 

I let code reviewers approve the fix and merge.

**Comment by llemeurfr** [comment]
@mickael-menu the CRL is updated (server-side) every 24h. In fact this is not expressed in the lcp spec, it is in the compliance rules. And it's true that it does not mean a "rule" to put this expiration delay to 1 day instead of 7. ok let's keep 7 days, it's really sufficient in practice.

**Pull request merged**
