### PR TITLE
Fix copy and print restrictions and information

### PR DESCRIPTION
**Pull request by qnga**
Because `license.charactersToCopyLeft` and `license.pagesToPrintLeft` were always null, right informations were wrong, and copy and print were unrestricted.

Fix https://github.com/readium/r2-testapp-kotlin/issues/267

### CODE REVIEW

**Comment by mickael-menu** [comment]
I will wait for the next beta to be out before merging this, as I already did all the tests. For information LCP copy is not yet implemented on Android, so this part was actually not really used.

**Comment by llemeurfr** [comment]
@mickael-menu when you say LCP copy is not yet implemented on Android, do you mean by the testapp, by all apps you know about, or simply because developers have so far hidden the copy button?

**Comment by mickael-menu** [comment]
@llemeurfr All of these actually. Do you know any app that actually implemented LCP copy on Android? Technically `r2-lcp-kotlin` is ready to save right consumption, but it's not trivial to actually implement it in the navigator or reading apps.

**Comment by llemeurfr** [comment]
In practice all app I've seen so far were blocking copy by deleting the copy/share button, which is far from being perfect, we all agree.

**Comment by mickael-menu** [comment]
Yes by "not implementing copy" I meant authorizing only the number of characters allowed in the license. The test app is disabling copy indeed.

**Review by mickael-menu — APPROVED** [review]
@qnga Works well, thanks!

**Pull request merged**
